// Multilingual dropdown options for the application

export const getMultilingualOptions = (language) => {
  const options = {
    en: {
      states: [
        { value: "", label: "Select State" },
        { value: "Kerala", label: "Kerala" },
        { value: "Tamil Nadu", label: "Tamil Nadu" },
        { value: "Karnataka", label: "Karnataka" },
        { value: "Andhra Pradesh", label: "Andhra Pradesh" },
        { value: "Telangana", label: "Telangana" },
        { value: "Maharashtra", label: "Maharashtra" },
        { value: "Gujarat", label: "Gujarat" },
        { value: "Rajasthan", label: "Rajasthan" },
        { value: "Punjab", label: "Punjab" },
        { value: "Haryana", label: "Haryana" },
        { value: "Uttar Pradesh", label: "Uttar Pradesh" },
        { value: "Madhya Pradesh", label: "Madhya Pradesh" },
        { value: "West Bengal", label: "West Bengal" },
        { value: "Odisha", label: "Odisha" },
        { value: "Bihar", label: "Bihar" },
      ],
      sectors: [
        { value: "", label: "All Sectors" },
        { value: "agriculture", label: "Agriculture" },
        { value: "horticulture", label: "Horticulture" },
        { value: "animal_husbandry", label: "Animal Husbandry" },
        { value: "fisheries", label: "Fisheries" },
        { value: "dairy", label: "Dairy" },
        { value: "rural_development", label: "Rural Development" },
      ],
      categories: [
        { value: "all", label: "All Categories" },
        { value: "seeds", label: "Seeds" },
        { value: "fertilizers", label: "Fertilizers" },
        { value: "pesticides", label: "Pesticides" },
        { value: "tools", label: "Tools & Equipment" },
        { value: "produce", label: "Produce" },
        { value: "livestock", label: "Livestock" },
      ],
      sortOptions: [
        { value: "name", label: "Name" },
        { value: "quantity", label: "Quantity" },
        { value: "price", label: "Price" },
        { value: "expiry_date", label: "Expiry Date" },
        { value: "last_updated", label: "Last Updated" },
      ],
    },
    hi: {
      states: [
        { value: "", label: "राज्य चुनें" },
        { value: "Kerala", label: "केरल" },
        { value: "Tamil Nadu", label: "तमिल नाडु" },
        { value: "Karnataka", label: "कर्नाटक" },
        { value: "Andhra Pradesh", label: "आंध्र प्रदेश" },
        { value: "Telangana", label: "तेलंगाना" },
        { value: "Maharashtra", label: "महाराष्ट्र" },
        { value: "Gujarat", label: "गुजरात" },
        { value: "Rajasthan", label: "राजस्थान" },
        { value: "Punjab", label: "पंजाब" },
        { value: "Haryana", label: "हरियाणा" },
        { value: "Uttar Pradesh", label: "उत्तर प्रदेश" },
        { value: "Madhya Pradesh", label: "मध्य प्रदेश" },
        { value: "West Bengal", label: "पश्चिम बंगाल" },
        { value: "Odisha", label: "ओडिशा" },
        { value: "Bihar", label: "बिहार" },
      ],
      sectors: [
        { value: "", label: "सभी क्षेत्र" },
        { value: "agriculture", label: "कृषि" },
        { value: "horticulture", label: "बागवानी" },
        { value: "animal_husbandry", label: "पशुपालन" },
        { value: "fisheries", label: "मत्स्य पालन" },
        { value: "dairy", label: "डेयरी" },
        { value: "rural_development", label: "ग्रामीण विकास" },
      ],
      categories: [
        { value: "all", label: "सभी श्रेणियां" },
        { value: "seeds", label: "बीज" },
        { value: "fertilizers", label: "उर्वरक" },
        { value: "pesticides", label: "कीटनाशक" },
        { value: "tools", label: "औजार और उपकरण" },
        { value: "produce", label: "उत्पादन" },
        { value: "livestock", label: "पशुधन" },
      ],
      sortOptions: [
        { value: "name", label: "नाम" },
        { value: "quantity", label: "मात्रा" },
        { value: "price", label: "कीमत" },
        { value: "expiry_date", label: "समाप्ति तिथि" },
        { value: "last_updated", label: "अंतिम अपडेट" },
      ],
    },
    ml: {
      states: [
        { value: "", label: "സംസ്ഥാനം തിരഞ്ഞെടുക്കുക" },
        { value: "Kerala", label: "കേരളം" },
        { value: "Tamil Nadu", label: "തമിഴ്‌നാട്" },
        { value: "Karnataka", label: "കർണാടക" },
        { value: "Andhra Pradesh", label: "ആന്ധ്രപ്രദേശ്" },
        { value: "Telangana", label: "തെലങ്കാന" },
        { value: "Maharashtra", label: "മഹാരാഷ്ട്ര" },
        { value: "Gujarat", label: "ഗുജറാത്ത്" },
        { value: "Rajasthan", label: "രാജസ്ഥാൻ" },
        { value: "Punjab", label: "പഞ്ചാബ്" },
        { value: "Haryana", label: "ഹരിയാണ" },
        { value: "Uttar Pradesh", label: "ഉത്തർപ്രദേശ്" },
        { value: "Madhya Pradesh", label: "മധ്യപ്രദേശ്" },
        { value: "West Bengal", label: "പശ്ചിമ ബംഗാൾ" },
        { value: "Odisha", label: "ഒഡിഷ" },
        { value: "Bihar", label: "ബീഹാർ" },
      ],
      sectors: [
        { value: "", label: "എല്ലാ മേഖലകളും" },
        { value: "agriculture", label: "കൃഷി" },
        { value: "horticulture", label: "തോട്ടകൃഷി" },
        { value: "animal_husbandry", label: "മൃഗസംരക്ഷണം" },
        { value: "fisheries", label: "മത്സ്യബന്ധനം" },
        { value: "dairy", label: "ഡയറി" },
        { value: "rural_development", label: "ഗ്രാമ വികസനം" },
      ],
      categories: [
        { value: "all", label: "എല്ലാ വിഭാഗങ്ങളും" },
        { value: "seeds", label: "വിത്തുകൾ" },
        { value: "fertilizers", label: "വളങ്ങൾ" },
        { value: "pesticides", label: "കീടനാശിനികൾ" },
        { value: "tools", label: "ഉപകരണങ്ങൾ" },
        { value: "produce", label: "ഉൽപ്പന്നങ്ങൾ" },
        { value: "livestock", label: "കന്നുകാലികൾ" },
      ],
      sortOptions: [
        { value: "name", label: "പേര്" },
        { value: "quantity", label: "അളവ്" },
        { value: "price", label: "വില" },
        { value: "expiry_date", label: "കാലാവധി" },
        { value: "last_updated", label: "അവസാന അപ്ഡേറ്റ്" },
      ],
    },
  };

  return options[language] || options.en;
};

export const getWeatherCityOptions = (language) => {
  const options = {
    en: [
      { value: "Kochi", label: "Kochi, Kerala" },
      { value: "Thiruvananthapuram", label: "Thiruvananthapuram, Kerala" },
      { value: "Kozhikode", label: "Kozhikode, Kerala" },
      { value: "Thrissur", label: "Thrissur, Kerala" },
      { value: "Kollam", label: "Kollam, Kerala" },
      { value: "Palakkad", label: "Palakkad, Kerala" },
      { value: "Kannur", label: "Kannur, Kerala" },
      { value: "Kasaragod", label: "Kasaragod, Kerala" },
    ],
    hi: [
      { value: "Kochi", label: "कोच्चि, केरल" },
      { value: "Thiruvananthapuram", label: "तिरुवनंतपुरम, केरल" },
      { value: "Kozhikode", label: "कोझिकोड, केरल" },
      { value: "Thrissur", label: "त्रिशूर, केरल" },
      { value: "Kollam", label: "कोल्लम, केरल" },
      { value: "Palakkad", label: "पालक्कड़, केरल" },
      { value: "Kannur", label: "कन्नूर, केरल" },
      { value: "Kasaragod", label: "कासरगोड, केरल" },
    ],
    ml: [
      { value: "Kochi", label: "കൊച്ചി, കേരളം" },
      { value: "Thiruvananthapuram", label: "തിരുവനന്തപുരം, കേരളം" },
      { value: "Kozhikode", label: "കോഴിക്കോട്, കേരളം" },
      { value: "Thrissur", label: "തൃശ്ശൂർ, കേരളം" },
      { value: "Kollam", label: "കൊല്ലം, കേരളം" },
      { value: "Palakkad", label: "പാലക്കാട്, കേരളം" },
      { value: "Kannur", label: "കണ്ണൂർ, കേരളം" },
      { value: "Kasaragod", label: "കാസർഗോഡ്, കേരളം" },
    ],
  };

  return options[language] || options.en;
};
